name: TA Quick Checker

on:
  workflow_dispatch: {}
  push:
    paths:
      - "COIN.txt"

permissions:
  contents: write

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run checker
        run: python scripts/check_coin.py

      - name: Commit OUTPUT.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add OUTPUT.md
          git commit -m "Update OUTPUT.md from TA checker" || echo "No changes to commit"
          git push
